version: '3.8'

services:
  misticfy:
    build:
      context: .
      dockerfile: Dockerfile
    image: misticfy-dev:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./:/app:delegated
    command: >
      dotnet run --no-launch-profile --project MisticFy.csproj --urls http://+:5000
    restart: unless-stopped
