<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="ErrorMessageResource.resx" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExceptionsBase\AuthErrors\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ErrorMessageResource.pt-BR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessageResource.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ErrorMessageResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessageResource.Designer.cs</LastGenOutput>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ErrorMessageResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessageResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
