// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisticFy.Context;

#nullable disable

namespace MisticFy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250918164747_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MisticFy.Models.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MusicId"));

                    b.Property<string>("MusicName")
                        .HasColumnType("longtext");

                    b.HasKey("MusicId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("MisticFy.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTO.SpotifyAlbumDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SpotifyAlbumDTO");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTO.SpotifyArtistDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SpotifyMusicDTOId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyMusicDTOId");

                    b.ToTable("SpotifyArtistDTO");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTOs.SpotifyMusicDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlbumId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("SpotifyMusicDTO");
                });

            modelBuilder.Entity("MisticFy.src.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("SpotifyUserId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MisticFy.Models.Playlist", b =>
                {
                    b.HasOne("MisticFy.src.Models.Users", null)
                        .WithMany("Playlists")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTO.SpotifyArtistDTO", b =>
                {
                    b.HasOne("MisticFy.src.DTO.DTOs.SpotifyMusicDTO", null)
                        .WithMany("Artists")
                        .HasForeignKey("SpotifyMusicDTOId");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTOs.SpotifyMusicDTO", b =>
                {
                    b.HasOne("MisticFy.src.DTO.DTO.SpotifyAlbumDTO", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.HasOne("MisticFy.Models.Playlist", null)
                        .WithMany("Musics")
                        .HasForeignKey("PlaylistId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MisticFy.Models.Playlist", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("MisticFy.src.DTO.DTOs.SpotifyMusicDTO", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("MisticFy.src.Models.Users", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
